#!/bin/bash
#eliminar virus


num=`ls /media`
num2=`ls /media/$num`
echo "eliminacion de virus"
echo "los archivos encontrados son:"

ls /media/$num/$num2

echo "se eliminaran los virus de la usb "$num2""


sudo rm -f -v /media/$num/$num2/autorun.inf /media/$num/$num2/*.lnk /media/$num/$num2/*.com /media/$num/$num2/recycler /media/$num/$num2/*.bat

echo "los virus se han eliminado"
