#!/bin/bash
#archivos modificados ayer

c=`date +'%b %e' -d "yesterday"`
echo "Se buscaran los archivos modificados el dia "$c" en el directorio $HOME"

echo "Los archivos modificados ayer son: "


sudo ls $HOME -lR | grep "$c"
