#!/bin/bash
#archivos modificados ayer
#autor:Johns

c=`date +'%b %e' -d "yesterday"`
echo "Se buscaran los archivos modificados el dia "$c""
echo "Los archivos modificados ayer son: "


sudo ls -l | grep "$c"
